In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
df = {
    "Emp_Id":[100,110,120,130,140],
    "Name" : ["Prem","Yug","Sonal","Arun","Vishnu"],
    "Dept" : ['IT','Teaching','Finance','IT','IT'],
    "Salary": [2000,4000,10000,300000,50000]
}

df = pd.DataFrame(data=df)

In [42]:
df

   Emp_Id    Name      Dept  Salary
0     100    Prem        IT    2000
1     110     Yug  Teaching    4000
2     120   Sonal   Finance   10000
3     130    Arun        IT  300000
4     140  Vishnu        IT   50000

In [43]:
print(df.sort_values(by = "Salary",ascending=False))

   Emp_Id    Name      Dept  Salary
3     130    Arun        IT  300000
4     140  Vishnu        IT   50000
2     120   Sonal   Finance   10000
1     110     Yug  Teaching    4000
0     100    Prem        IT    2000

In [44]:
# update salary
df.loc[df['Dept']=="IT",'Salary'] = 450000

In [45]:
df

   Emp_Id    Name      Dept  Salary
0     100    Prem        IT  450000
1     110     Yug  Teaching    4000
2     120   Sonal   Finance   10000
3     130    Arun        IT  450000
4     140  Vishnu        IT  450000

In [46]:
# count of emp in each dept
print(df['Dept'].value_counts())

Dept
IT          3
Teaching    1
Finance     1
Name: count, dtype: int64

In [47]:
# max sal
print(df.loc[df['Dept']=='IT','Salary'].max())

450000

In [48]:
print(df.iloc[3])

Emp_Id       130
Name        Arun
Dept          IT
Salary    450000
Name: 3, dtype: object

In [49]:
df.drop(columns='Name',inplace=True)
df

   Emp_Id      Dept  Salary
0     100        IT  450000
1     110  Teaching    4000
2     120   Finance   10000
3     130        IT  450000
4     140        IT  450000

In [ ]:
new_salary = 1000  # amount to add
df['Salary'] = df['Salary'] + new_salary

450000

In [56]:
new_salary = 5000
df.loc[:, "Salary"] = df.loc[:, "Salary"] + new_salary

In [57]:
df.loc[df["Dept"]=="Teaching","Salary"] += new_salary
df

   Emp_Id      Dept  Salary
0     100        IT  458000
1     110  Teaching   18000
2     120   Finance   18000
3     130        IT  458000
4     140        IT  458000

In [61]:
print(df.loc[df['Salary'].idxmax()])
print(df['Salary'].max())

Emp_Id       100
Dept          IT
Salary    458000
Name: 0, dtype: object
458000

In [62]:
print(df.groupby('Dept')['Salary'].mean())

Dept
Finance      18000.0
IT          458000.0
Teaching     18000.0
Name: Salary, dtype: float64