In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = {
    "Employee": ["Asha", "Ravi", "Neha", "Arjun", "Maya", "Kabir",
                 "Isha", "Dev", "Sara", "Omar", "Tara", "Vikram"],
    "Department": ["Sales", "IT", "HR", "IT", "Sales", "HR",
                   "IT", "Sales", "HR", "IT", "Sales", "HR"],
    "City": ["Mumbai", "Pune", "Mumbai", "Delhi", "Pune", "Delhi",
             "Mumbai", "Delhi", "Pune", "Pune", "Mumbai", "Delhi"],
    "Experience": [2, 5, 3, 8, 4, 6, 1, 7, 2, 3, 6, 4],
    "Salary": [45000, 80000, 52000, 120000, 65000, 75000,
              48000, 95000, 50000, 70000, 85000, 62000],
    "Performance": [4, 5, 3, 5, 4, 4, 3, 5, 4, 3, 5, 4]
}

df = pd.DataFrame(data)

In [4]:
df.head()

  Employee Department    City  Experience  Salary  Performance
0     Asha      Sales  Mumbai           2   45000            4
1     Ravi         IT    Pune           5   80000            5
2     Neha         HR  Mumbai           3   52000            3
3    Arjun         IT   Delhi           8  120000            5
4     Maya      Sales    Pune           4   65000            4

In [5]:
df.groupby(by="Department")["Salary"].mean()

Department
HR       59750.0
IT       79500.0
Sales    72500.0
Name: Salary, dtype: float64

In [6]:
df.groupby(by='Department')['Salary'].agg(["mean","min","max","count"])

               mean    min     max  count
Department
HR          59750.0  50000   75000      4
IT          79500.0  48000  120000      4
Sales       72500.0  45000   95000      4

In [7]:
df.groupby(['Department','City'])['Salary'].mean()

Department  City
HR          Delhi      68500.0
            Mumbai     52000.0
            Pune       50000.0
IT          Delhi     120000.0
            Mumbai     48000.0
            Pune       75000.0
Sales       Delhi      95000.0
            Mumbai     65000.0
            Pune       65000.0
Name: Salary, dtype: float64

In [9]:
df['DeptAvgSalary'] = df.groupby("Department")['Salary'].transform('mean')
df

   Employee Department    City  Experience  Salary  Performance  DeptAvgSalary
0      Asha      Sales  Mumbai           2   45000            4        72500.0
1      Ravi         IT    Pune           5   80000            5        79500.0
2      Neha         HR  Mumbai           3   52000            3        59750.0
3     Arjun         IT   Delhi           8  120000            5        79500.0
4      Maya      Sales    Pune           4   65000            4        72500.0
5     Kabir         HR   Delhi           6   75000            4        59750.0
6      Isha         IT  Mumbai           1   48000            3        79500.0
7       Dev      Sales   Delhi           7   95000            5        72500.0
8      Sara         HR    Pune           2   50000            4        59750.0
9      Omar         IT    Pune           3   70000            3        79500.0
10     Tara      Sales  Mumbai           6   85000            5        72500.0
11   Vikram         HR   Delhi           4   62000            4        59750.0

In [14]:
df.groupby("Department").filter(lambda group: len(group) >= 4 )

   Employee Department    City  Experience  Salary  Performance  DeptAvgSalary
0      Asha      Sales  Mumbai           2   45000            4        72500.0
1      Ravi         IT    Pune           5   80000            5        79500.0
2      Neha         HR  Mumbai           3   52000            3        59750.0
3     Arjun         IT   Delhi           8  120000            5        79500.0
4      Maya      Sales    Pune           4   65000            4        72500.0
5     Kabir         HR   Delhi           6   75000            4        59750.0
6      Isha         IT  Mumbai           1   48000            3        79500.0
7       Dev      Sales   Delhi           7   95000            5        72500.0
8      Sara         HR    Pune           2   50000            4        59750.0
9      Omar         IT    Pune           3   70000            3        79500.0
10     Tara      Sales  Mumbai           6   85000            5        72500.0
11   Vikram         HR   Delhi           4   62000            4        59750.0

In [15]:
df.loc[df['Salary'].idxmax()]

Employee           Arjun
Department            IT
City               Delhi
Experience             8
Salary            120000
Performance            5
DeptAvgSalary    79500.0
Name: 3, dtype: object

In [20]:
print(df[['City','Experience']])

      City  Experience
0   Mumbai           2
1     Pune           5
2   Mumbai           3
3    Delhi           8
4     Pune           4
5    Delhi           6
6   Mumbai           1
7    Delhi           7
8     Pune           2
9     Pune           3
10  Mumbai           6
11   Delhi           4

In [22]:
df.iloc[[5,6,7]][['City','Experience','Salary']]

     City  Experience  Salary
5   Delhi           6   75000
6  Mumbai           1   48000
7   Delhi           7   95000